Data updates je
Public-Health-Scotland/care-and-wellbeing-dashboard pull request #6
Opened 2023-07-13 08:09 UTC by Jen-e2

Updates to:

* gender pay gap
* camhs
* employees on the living wage
* heart attack - including adding rate/number

2023-07-13 13:57 UTC, iainma09 requested changes
All looks good! One minor change to the heart attack admissions: the  data table has a decimal place where its not needed.

2023-07-14 08:38 UTC, Jen-e2 commented
![image](https://github.com/Public-Health-Scotland/care-and-wellbeing-dashboard/assets/91132691/d6077fab-ea57-4d26-b21d-3a855526fd9b)

Changed as requested

2023-07-14 09:02 UTC, iainma09 approved these changes

2023-07-14 09:03 UTC, merged

2023-07-14 09:03 UTC, iainma09 commented
All looks, good, thanks for the screen grab